<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = array(
            array("name" => "Handmade Shell", "console_id" => "ammo.handmade.shell"),
            array("name" => "Nailgun Nails", "console_id" => "ammo.nailgun.nails"),
            array("name" => "Pistol Bullet", "console_id" => "ammo.pistol"),
            array("name" => "Incendiary Pistol Bullet", "console_id" => "ammo.pistol.fire"),
            array("name" => "HV Pistol Ammo", "console_id" => "ammo.pistol.hv"),
            array("name" => "5.56 Rifle Ammo", "console_id" => "ammo.rifle"),
            array("name" => "Explosive 5.56 Rifle Ammo", "console_id" => "ammo.rifle.explosive"),
            array("name" => "HV 5.56 Rifle Ammo", "console_id" => "ammo.rifle.hv"),
            array("name" => "Incendiary 5.56 Rifle Ammo", "console_id" => "ammo.rifle.incendiary"),
            array("name" => "Rocket", "console_id" => "ammo.rocket.basic"),
            array("name" => "Incendiary Rocket", "console_id" => "ammo.rocket.fire"),
            array("name" => "High Velocity Rocket", "console_id" => "ammo.rocket.hv"),
            array("name" => "Smoke Rocket WIP!!!!", "console_id" => "ammo.rocket.smoke"),
            array("name" => "12 Gauge Buckshot", "console_id" => "ammo.shotgun"),
            array("name" => "12 Gauge Slug", "console_id" => "ammo.shotgun.slug"),
            array("name" => "Anti-Radiation Pills", "console_id" => "antiradpills"),
            array("name" => "Apple", "console_id" => "apple"),
            array("name" => "Rotten Apple", "console_id" => "apple.spoiled"),
            array("name" => "Bone Arrow", "console_id" => "arrow.bone"),
            array("name" => "Fire Arrow", "console_id" => "arrow.fire"),
            array("name" => "High Velocity Arrow", "console_id" => "arrow.hv"),
            array("name" => "Wooden Arrow", "console_id" => "arrow.wooden"),
            array("name" => "Hide Boots", "console_id" => "attire.hide.boots"),
            array("name" => "Hide Halterneck", "console_id" => "attire.hide.helterneck"),
            array("name" => "Hide Pants", "console_id" => "attire.hide.pants"),
            array("name" => "Hide Poncho", "console_id" => "attire.hide.poncho"),
            array("name" => "Hide Skirt", "console_id" => "attire.hide.skirt"),
            array("name" => "Hide Vest", "console_id" => "attire.hide.vest"),
            array("name" => "Reindeer Antlers", "console_id" => "attire.reindeer.headband"),
            array("name" => "Auto Turret", "console_id" => "autoturret"),
            array("name" => "Salvaged Axe", "console_id" => "axe.salvaged"),
            array("name" => "Bandage", "console_id" => "bandage"),
            array("name" => "Concrete Barricade", "console_id" => "barricade.concrete"),
            array("name" => "Metal Barricade", "console_id" => "barricade.metal"),
            array("name" => "Sandbag Barricade", "console_id" => "barricade.sandbags"),
            array("name" => "Stone Barricade", "console_id" => "barricade.stone"),
            array("name" => "Wooden Barricade", "console_id" => "barricade.wood"),
            array("name" => "Barbed Wooden Barricade", "console_id" => "barricade.woodwire"),
            array("name" => "Battery - Small", "console_id" => "battery.small"),
            array("name" => "Barbeque", "console_id" => "bbq"),
            array("name" => "Raw Bear Meat", "console_id" => "bearmeat"),
            array("name" => "Burnt Bear Meat", "console_id" => "bearmeat.burned"),
            array("name" => " Cooked Bear Meat", "console_id" => "bearmeat.cooked"),
            array("name" => "Bed", "console_id" => "bed"),
            array("name" => "Black Raspberries", "console_id" => "black.raspberries"),
            array("name" => "Bleach", "console_id" => "bleach"),
            array("name" => "Blood", "console_id" => "blood"),
            array("name" => "Blueberries", "console_id" => "blueberries"),
            array("name" => "Blueprint", "console_id" => "blueprintbase"),
            array("name" => "Bone Armor", "console_id" => "bone.armor.suit"),
            array("name" => "Bone Club", "console_id" => "bone.club"),
            array("name" => "Bone Fragments", "console_id" => "bone.fragments"),
            array("name" => "Bota Bag", "console_id" => "botabag"),
            array("name" => "Hunting Bow", "console_id" => "bow.hunting"),
            array("name" => "Repair Bench", "console_id" => "box.repair.bench"),
            array("name" => "Wood Storage Box", "console_id" => "box.wooden"),
            array("name" => "Large Wood Box", "console_id" => "box.wooden.large"),
            array("name" => "Bucket Helmet", "console_id" => "bucket.helmet"),
            array("name" => "Water Bucket", "console_id" => "bucket.water"),
            array("name" => "Building Plan", "console_id" => "building.planner"),
            array("name" => "Leather Gloves", "console_id" => "burlap.gloves"),
            array("name" => "Burlap Headwrap", "console_id" => "burlap.headwrap"),
            array("name" => "Burlap Shirt", "console_id" => "burlap.shirt"),
            array("name" => "Burlap Shoes", "console_id" => "burlap.shoes"),
            array("name" => "Burlap Trousers", "console_id" => "burlap.trousers"),
            array("name" => "Cactus Flesh", "console_id" => "cactusflesh"),
            array("name" => "Camp Fire", "console_id" => "campfire"),
            array("name" => "Can of Beans", "console_id" => "can.beans"),
            array("name" => "Empty Can Of Beans", "console_id" => "can.beans.empty"),
            array("name" => "Can of Tuna", "console_id" => "can.tuna"),
            array("name" => "Empty Tuna Can", "console_id" => "can.tuna.empty"),
            array("name" => "Candy Cane", "console_id" => "candycane"),
            array("name" => "Candy Cane Club", "console_id" => "candycaneclub"),
            array("name" => "CCTV Camera", "console_id" => "cctv.camera"),
            array("name" => "Ceiling Light", "console_id" => "ceilinglight"),
            array("name" => "Chair", "console_id" => "chair"),
            array("name" => "Charcoal", "console_id" => "charcoal"),
            array("name" => "Burnt Chicken", "console_id" => "chicken.burned"),
            array("name" => "Cooked Chicken", "console_id" => "chicken.cooked"),
            array("name" => "Raw Chicken Breast", "console_id" => "chicken.raw"),
            array("name" => "Spoiled Chicken", "console_id" => "chicken.spoiled"),
            array("name" => "Chocolate Bar", "console_id" => "chocholate"),
            array("name" => "Corn Clone", "console_id" => "clone.corn"),
            array("name" => "Hemp Clone", "console_id" => "clone.hemp"),
            array("name" => "Pumpkin Plant Clone", "console_id" => "clone.pumpkin"),
            array("name" => "Cloth", "console_id" => "cloth"),
            array("name" => "Coal :(", "console_id" => "coal"),
            array("name" => "Coffee Can Helmet", "console_id" => "coffeecan.helmet"),
            array("name" => "Corn", "console_id" => "corn"),
            array("name" => "Crossbow", "console_id" => "crossbow"),
            array("name" => "Crude Oil", "console_id" => "crude.oil"),
            array("name" => "Tool Cupboard", "console_id" => "cupboard.tool"),
            array("name" => "Bone Helmet", "console_id" => "deer.skull.mask"),
            array("name" => "Burnt Deer Meat", "console_id" => "deermeat.burned"),
            array("name" => "Cooked Deer Meat", "console_id" => "deermeat.cooked"),
            array("name" => "Raw Deer Meat", "console_id" => "deermeat.raw"),
            array("name" => "Door Closer", "console_id" => "door.closer"),
            array("name" => "Sheet Metal Double Door", "console_id" => "door.double.hinged.metal"),
            array("name" => "Armored Double Door", "console_id" => "door.double.hinged.toptier"),
            array("name" => "Wood Double Door", "console_id" => "door.double.hinged.wood"),
            array("name" => "Sheet Metal Door", "console_id" => "door.hinged.metal"),
            array("name" => "Armored Door", "console_id" => "door.hinged.toptier"),
            array("name" => "Wooden Door", "console_id" => "door.hinged.wood"),
            array("name" => "Door Key", "console_id" => "door.key"),
            array("name" => "Drop Box", "console_id" => "dropbox"),
            array("name" => "Duct Tape", "console_id" => "ducttape"),
            array("name" => "Satchel Charge", "console_id" => "explosive.satchel"),
            array("name" => "Timed Explosive Charge", "console_id" => "explosive.timed"),
            array("name" => "Explosives", "console_id" => "explosives"),
            array("name" => "m-facialhair01", "console_id" => "facialhair.style01"),
            array("name" => "Animal Fat", "console_id" => "fat.animal"),
            array("name" => "f-hairstyle-1", "console_id" => "female_hairstyle_01"),
            array("name" => "f-hairstyle-2", "console_id" => "female_hairstyle_02"),
            array("name" => "f-hairstyle-3", "console_id" => "female_hairstyle_03"),
            array("name" => "f-armpit01", "console_id" => "femalearmpithair.style01"),
            array("name" => "f-eyebrow01", "console_id" => "femaleeyebrow.style01"),
            array("name" => "f-pubic01", "console_id" => "femalepubichair.style01"),
            array("name" => "Stone Fireplace", "console_id" => "fireplace.stone"),
            array("name" => "Cooked Fish", "console_id" => "fish.cooked"),
            array("name" => "Minnows", "console_id" => "fish.minnows"),
            array("name" => "Raw Fish", "console_id" => "fish.raw"),
            array("name" => "Small Trout", "console_id" => "fish.troutsmall"),
            array("name" => "Survival Fish Trap", "console_id" => "fishtrap.small"),
            array("name" => "Flame Thrower", "console_id" => "flamethrower"),
            array("name" => "Flame Turret", "console_id" => "flameturret"),
            array("name" => "Flare", "console_id" => "flare"),
            array("name" => "Flashlight", "console_id" => "flashlight.held"),
            array("name" => "Floor grill", "console_id" => "floor.grill"),
            array("name" => "Ladder Hatch", "console_id" => "floor.ladder.hatch"),
            array("name" => "Fridge", "console_id" => "fridge"),
            array("name" => "Acoustic Guitar", "console_id" => "fun.guitar"),
            array("name" => "Furnace", "console_id" => "furnace"),
            array("name" => "Large Furnace", "console_id" => "furnace.large"),
            array("name" => "High External Stone Gate", "console_id" => "gates.external.high.stone"),
            array("name" => "High External Wooden Gate", "console_id" => "gates.external.high.wood"),
            array("name" => "Gears", "console_id" => "gears"),
            array("name" => "Wind Turbine", "console_id" => "generator.wind.scrap"),
            array("name" => "Glowing Eyes", "console_id" => "gloweyes"),
            array("name" => "Glue", "console_id" => "glue"),
            array("name" => "Granola Bar", "console_id" => "granolabar"),
            array("name" => "Beancan Grenade", "console_id" => "grenade.beancan"),
            array("name" => "F1 Grenade", "console_id" => "grenade.f1"),
            array("name" => "Gun Powder", "console_id" => "gunpowder"),
            array("name" => "Shotgun Trap", "console_id" => "guntrap"),
            array("name" => "Hammer", "console_id" => "hammer"),
            array("name" => "Salvaged Hammer", "console_id" => "hammer.salvaged"),
            array("name" => "Beenie Hat", "console_id" => "hat.beenie"),
            array("name" => "Boonie Hat", "console_id" => "hat.boonie"),
            array("name" => "Candle Hat", "console_id" => "hat.candle"),
            array("name" => "Baseball Cap", "console_id" => "hat.cap"),
            array("name" => "Miners Hat", "console_id" => "hat.miner"),
            array("name" => "Wolf Headdress", "console_id" => "hat.wolf"),
            array("name" => "Hatchet", "console_id" => "hatchet"),
            array("name" => "Hazmat Suit", "console_id" => "hazmatsuit"),
            array("name" => "Scientist Suit", "console_id" => "hazmatsuit_scientist"),
            array("name" => "Heavy Plate Helmet", "console_id" => "heavy.plate.helmet"),
            array("name" => "Heavy Plate Jacket", "console_id" => "heavy.plate.jacket"),
            array("name" => "Heavy Plate Pants", "console_id" => "heavy.plate.pants"),
            array("name" => "Hoodie", "console_id" => "hoodie"),
            array("name" => "High Quality Metal Ore", "console_id" => "hq.metal.ore"),
            array("name" => "Burnt Human Meat", "console_id" => "humanmeat.burned"),
            array("name" => "Cooked Human Meat", "console_id" => "humanmeat.cooked"),
            array("name" => "Raw Human Meat", "console_id" => "humanmeat.raw"),
            array("name" => "Spoiled Human Meat", "console_id" => "humanmeat.spoiled"),
            array("name" => "Salvaged Icepick", "console_id" => "icepick.salvaged"),
            array("name" => "Jacket", "console_id" => "jacket"),
            array("name" => "Snow Jacket - Red", "console_id" => "jacket.snow"),
            array("name" => "Jack O Lantern Angry", "console_id" => "jackolantern.angry"),
            array("name" => "Jack O Lantern Happy", "console_id" => "jackolantern.happy"),
            array("name" => "Bone Knife", "console_id" => "knife.bone"),
            array("name" => "Wooden Ladder", "console_id" => "ladder.wooden.wall"),
            array("name" => "Lantern", "console_id" => "lantern"),
            array("name" => "Large Medkit", "console_id" => "largemedkit"),
            array("name" => "Leather", "console_id" => "leather"),
            array("name" => "M249", "console_id" => "lmg.m249"),
            array("name" => "Code Lock", "console_id" => "lock.code"),
            array("name" => "Key Lock", "console_id" => "lock.key"),
            array("name" => "Locker", "console_id" => "locker"),
            array("name" => "Longsword", "console_id" => "longsword"),
            array("name" => "Low Grade Fuel", "console_id" => "lowgradefuel"),
            array("name" => "Mace", "console_id" => "mace"),
            array("name" => "Machete", "console_id" => "machete"),
            array("name" => "Mail Box", "console_id" => "mailbox"),
            array("name" => "m-facialhair02", "console_id" => "male.facialhair.style02"),
            array("name" => "m-hairstyle-1", "console_id" => "male_hairstyle_01"),
            array("name" => "m-hairstyle-2", "console_id" => "male_hairstyle_02"),
            array("name" => "m-hairstyle-3", "console_id" => "male_hairstyle_03"),
            array("name" => "m-armpit01", "console_id" => "malearmpithair.style01"),
            array("name" => "m-eyebrow01", "console_id" => "maleeyebrow.style01"),
            array("name" => "m-pubic01", "console_id" => "malepubichair.style01"),
            array("name" => "Paper Map", "console_id" => "map"),
            array("name" => "Improvised Balaclava", "console_id" => "mask.balaclava"),
            array("name" => "Bandana Mask", "console_id" => "mask.bandana"),
            array("name" => "Raw Pork", "console_id" => "meat.boar"),
            array("name" => "Burnt Pork", "console_id" => "meat.pork.burned"),
            array("name" => "Cooked Pork", "console_id" => "meat.pork.cooked"),
            array("name" => "Metal Facemask", "console_id" => "metal.facemask"),
            array("name" => "Metal Fragments", "console_id" => "metal.fragments"),
            array("name" => "Metal Ore", "console_id" => "metal.ore"),
            array("name" => "Metal Chest Plate", "console_id" => "metal.plate.torso"),
            array("name" => "High Quality Metal", "console_id" => "metal.refined"),
            array("name" => "Metal Blade", "console_id" => "metalblade"),
            array("name" => "Metal Pipe", "console_id" => "metalpipe"),
            array("name" => "Metal Spring", "console_id" => "metalspring"),
            array("name" => "Pump Jack", "console_id" => "mining.pumpjack"),
            array("name" => "Mining Quarry", "console_id" => "mining.quarry"),
            array("name" => "Mushroom", "console_id" => "mushroom"),
            array("name" => "Note", "console_id" => "note"),
            array("name" => "Pants", "console_id" => "pants"),
            array("name" => "Shorts", "console_id" => "pants.shorts"),
            array("name" => "Paper", "console_id" => "paper"),
            array("name" => "Pickaxe", "console_id" => "pickaxe"),
            array("name" => "Eoka Pistol", "console_id" => "pistol.eoka"),
            array("name" => "M92 Pistol", "console_id" => "pistol.m92"),
            array("name" => "Nailgun", "console_id" => "pistol.nailgun"),
            array("name" => "Python Revolver", "console_id" => "pistol.python"),
            array("name" => "Revolver", "console_id" => "pistol.revolver"),
            array("name" => "Semi-Automatic Pistol", "console_id" => "pistol.semiauto"),
            array("name" => "Large Planter Box", "console_id" => "planter.large"),
            array("name" => "Small Planter Box", "console_id" => "planter.small"),
            array("name" => "Pookie Bear", "console_id" => "pookie.bear"),
            array("name" => "Empty Propane Tank", "console_id" => "propanetank"),
            array("name" => "Pumpkin", "console_id" => "pumpkin"),
            array("name" => "Research Table", "console_id" => "research.table"),
            array("name" => "Research Paper", "console_id" => "researchpaper"),
            array("name" => "Assault Rifle", "console_id" => "rifle.ak"),
            array("name" => "Bolt Action Rifle", "console_id" => "rifle.bolt"),
            array("name" => "LR-300 Assault Rifle", "console_id" => "rifle.lr300"),
            array("name" => "Semi-Automatic Rifle", "console_id" => "rifle.semiauto"),
            array("name" => "Rifle Body", "console_id" => "riflebody"),
            array("name" => "Riot Helmet", "console_id" => "riot.helmet"),
            array("name" => "Road Sign Jacket", "console_id" => "roadsign.jacket"),
            array("name" => "Road Sign Kilt", "console_id" => "roadsign.kilt"),
            array("name" => "Road Signs", "console_id" => "roadsigns"),
            array("name" => "Rock", "console_id" => "rock"),
            array("name" => "Rocket Launcher", "console_id" => "rocket.launcher"),
            array("name" => "Rope", "console_id" => "rope"),
            array("name" => "Rug", "console_id" => "rug"),
            array("name" => "Rug Bear Skin", "console_id" => "rug.bear"),
            array("name" => "Salvaged Cleaver", "console_id" => "salvaged.cleaver"),
            array("name" => "Salvaged Sword", "console_id" => "salvaged.sword"),
            array("name" => "Santa Hat", "console_id" => "santahat"),
            array("name" => "Scarecrow", "console_id" => "scarecrow"),
            array("name" => "Scrap", "console_id" => "scrap"),
            array("name" => "Search Light", "console_id" => "searchlight"),
            array("name" => "Corn Seed", "console_id" => "seed.corn"),
            array("name" => "Hemp Seed", "console_id" => "seed.hemp"),
            array("name" => "Pumpkin Seed", "console_id" => "seed.pumpkin"),
            array("name" => "Semi Automatic Body", "console_id" => "semibody"),
            array("name" => "Sewing Kit", "console_id" => "sewingkit"),
            array("name" => "Sheet Metal", "console_id" => "sheetmetal"),
            array("name" => "Salvaged Shelves", "console_id" => "shelves"),
            array("name" => "Shirt", "console_id" => "shirt.collared"),
            array("name" => "Tank Top", "console_id" => "shirt.tanktop"),
            array("name" => "Boots", "console_id" => "shoes.boots"),
            array("name" => "Double Barrel Shotgun", "console_id" => "shotgun.double"),
            array("name" => "Pump Shotgun", "console_id" => "shotgun.pump"),
            array("name" => "Waterpipe Shotgun", "console_id" => "shotgun.waterpipe"),
            array("name" => "Metal horizontal embrasure", "console_id" => "shutter.metal.embrasure.a"),
            array("name" => "Metal Vertical embrasure", "console_id" => "shutter.metal.embrasure.b"),
            array("name" => "Wood Shutters", "console_id" => "shutter.wood.a"),
            array("name" => "Two Sided Hanging Sign", "console_id" => "sign.hanging"),
            array("name" => "Large Banner Hanging", "console_id" => "sign.hanging.banner.large"),
            array("name" => "Two Sided Ornate Hanging Sign", "console_id" => "sign.hanging.ornate"),
            array("name" => "Landscape Picture Frame", "console_id" => "sign.pictureframe.landscape"),
            array("name" => "Portrait Picture Frame", "console_id" => "sign.pictureframe.portrait"),
            array("name" => "Tall Picture Frame", "console_id" => "sign.pictureframe.tall"),
            array("name" => "XL Picture Frame", "console_id" => "sign.pictureframe.xl"),
            array("name" => "XXL Picture Frame", "console_id" => "sign.pictureframe.xxl"),
            array("name" => "Large Banner on pole", "console_id" => "sign.pole.banner.large"),
            array("name" => "Double Sign Post", "console_id" => "sign.post.double"),
            array("name" => "Single Sign Post", "console_id" => "sign.post.single"),
            array("name" => "One Sided Town Sign Post", "console_id" => "sign.post.town"),
            array("name" => "Two Sided Town Sign Post", "console_id" => "sign.post.town.roof"),
            array("name" => "Huge Wooden Sign", "console_id" => "sign.wooden.huge"),
            array("name" => "Large Wooden Sign", "console_id" => "sign.wooden.large"),
            array("name" => "Wooden Sign", "console_id" => "sign.wooden.medium"),
            array("name" => "Small Wooden Sign", "console_id" => "sign.wooden.small"),
            array("name" => "Human Skull", "console_id" => "skull.human"),
            array("name" => "Wolf Skull", "console_id" => "skull.wolf"),
            array("name" => "Skull Fire Pit", "console_id" => "skull_fire_pit"),
            array("name" => "Sleeping Bag", "console_id" => "sleepingbag"),
            array("name" => "Small Oil Refinery", "console_id" => "small.oil.refinery"),
            array("name" => "Small Water Bottle", "console_id" => "smallwaterbottle"),
            array("name" => "Custom SMG", "console_id" => "smg.2"),
            array("name" => "MP5A4", "console_id" => "smg.mp5"),
            array("name" => "Thompson", "console_id" => "smg.thompson"),
            array("name" => "SMG Body", "console_id" => "smgbody"),
            array("name" => "Snowball", "console_id" => "snowball"),
            array("name" => "Snowman", "console_id" => "snowman"),
            array("name" => "Stone Spear", "console_id" => "spear.stone"),
            array("name" => "Wooden Spear", "console_id" => "spear.wooden"),
            array("name" => "Wooden Floor Spikes", "console_id" => "spikes.floor"),
            array("name" => "Spinning wheel", "console_id" => "spinner.wheel"),
            array("name" => "Small Stash", "console_id" => "stash.small"),
            array("name" => "Sticks", "console_id" => "sticks"),
            array("name" => "SUPER Stocking", "console_id" => "stocking.large"),
            array("name" => "Small Stocking", "console_id" => "stocking.small"),
            array("name" => "Stone Pickaxe", "console_id" => "stone.pickaxe"),
            array("name" => "Stone Hatchet", "console_id" => "stonehatchet"),
            array("name" => "Stones", "console_id" => "stones"),
            array("name" => "Sulfur", "console_id" => "sulfur"),
            array("name" => "Sulfur Ore", "console_id" => "sulfur.ore"),
            array("name" => "Supply Signal", "console_id" => "supply.signal"),
            array("name" => "Survey Charge", "console_id" => "surveycharge"),
            array("name" => "Medical Syringe", "console_id" => "syringe.medical"),
            array("name" => "Table", "console_id" => "table"),
            array("name" => "Reactive Target", "console_id" => "target.reactive"),
            array("name" => "Targeting Computer", "console_id" => "targeting.computer"),
            array("name" => "Tarp", "console_id" => "tarp"),
            array("name" => "Tech Trash", "console_id" => "techparts"),
            array("name" => "Binoculars", "console_id" => "tool.binoculars"),
            array("name" => "Camera", "console_id" => "tool.camera"),
            array("name" => "Torch", "console_id" => "torch"),
            array("name" => "Snap Trap", "console_id" => "trap.bear"),
            array("name" => "Land Mine", "console_id" => "trap.landmine"),
            array("name" => "T-Shirt", "console_id" => "tshirt"),
            array("name" => "Longsleeve T-Shirt", "console_id" => "tshirt.long"),
            array("name" => "Tuna Can Lamp", "console_id" => "tunalight"),
            array("name" => "Vending Machine", "console_id" => "vending.machine"),
            array("name" => "High External Wooden Wall", "console_id" => "wall.external.high"),
            array("name" => "High External Stone Wall", "console_id" => "wall.external.high.stone"),
            array("name" => "Prison Cell Wall", "console_id" => "wall.frame.cell"),
            array("name" => "Prison Cell Gate", "console_id" => "wall.frame.cell.gate"),
            array("name" => "Chainlink Fence", "console_id" => "wall.frame.fence"),
            array("name" => "Chainlink Fence Gate", "console_id" => "wall.frame.fence.gate"),
            array("name" => "Garage Door", "console_id" => "wall.frame.garagedoor"),
            array("name" => "Netting", "console_id" => "wall.frame.netting"),
            array("name" => "Shop Front", "console_id" => "wall.frame.shopfront"),
            array("name" => "Metal Shop Front", "console_id" => "wall.frame.shopfront.metal"),
            array("name" => "Metal Window Bars", "console_id" => "wall.window.bars.metal"),
            array("name" => "Reinforced Window Bars", "console_id" => "wall.window.bars.toptier"),
            array("name" => "Wooden Window Bars", "console_id" => "wall.window.bars.wood"),
            array("name" => "Reinforced Glass Window", "console_id" => "wall.window.glass.reinforced"),
            array("name" => "Water", "console_id" => "water"),
            array("name" => "Water Barrel", "console_id" => "water.barrel"),
            array("name" => "Large Water Catcher", "console_id" => "water.catcher.large"),
            array("name" => "Small Water Catcher", "console_id" => "water.catcher.small"),
            array("name" => "Water Purifier", "console_id" => "water.purifier"),
            array("name" => "Salt Water", "console_id" => "water.salt"),
            array("name" => "Water Jug", "console_id" => "waterjug"),
            array("name" => "Weapon flashlight", "console_id" => "weapon.mod.flashlight"),
            array("name" => "Holosight", "console_id" => "weapon.mod.holosight"),
            array("name" => "Weapon Lasersight", "console_id" => "weapon.mod.lasersight"),
            array("name" => "Muzzle Boost", "console_id" => "weapon.mod.muzzleboost"),
            array("name" => "Muzzle Brake", "console_id" => "weapon.mod.muzzlebrake"),
            array("name" => "Silencer", "console_id" => "weapon.mod.silencer"),
            array("name" => "Simple Handmade Sight", "console_id" => "weapon.mod.simplesight"),
            array("name" => "4x Zoom Scope", "console_id" => "weapon.mod.small.scope"),
            array("name" => "Burnt Wolf Meat", "console_id" => "wolfmeat.burned"),
            array("name" => "Cooked Wolf Meat", "console_id" => "wolfmeat.cooked"),
            array("name" => "Raw Wolf Meat", "console_id" => "wolfmeat.raw"),
            array("name" => "Spoiled Wolf Meat", "console_id" => "wolfmeat.spoiled"),
            array("name" => "Wood", "console_id" => "wood"),
            array("name" => "Wood Armor Helmet", "console_id" => "wood.armor.helmet"),
            array("name" => "Wood Chestplate", "console_id" => "wood.armor.jacket"),
            array("name" => "Wood Armor Pants", "console_id" => "wood.armor.pants"),
            array("name" => "Work Bench Level 1", "console_id" => "workbench1"),
            array("name" => "Work Bench Level 2", "console_id" => "workbench2"),
            array("name" => "Work Bench Level 3", "console_id" => "workbench3"),
            array("name" => "Decorative Baubels", "console_id" => "xmas.decoration.baubels"),
            array("name" => "Decorative Plastic Candy Canes", "console_id" => "xmas.decoration.candycanes"),
            array("name" => "Decorative Gingerbread Men", "console_id" => "xmas.decoration.gingerbreadmen"),
            array("name" => "Tree Lights", "console_id" => "xmas.decoration.lights"),
            array("name" => "Decorative Pinecones", "console_id" => "xmas.decoration.pinecone"),
            array("name" => "Star Tree Topper", "console_id" => "xmas.decoration.star"),
            array("name" => "Decorative Tinsel", "console_id" => "xmas.decoration.tinsel"),
            array("name" => "Festive Doorway Garland", "console_id" => "xmas.door.garland"),
            array("name" => "Christmas Lights", "console_id" => "xmas.lightstring"),
            array("name" => "Large Present", "console_id" => "xmas.present.large"),
            array("name" => "Medium Present", "console_id" => "xmas.present.medium"),
            array("name" => "Small Present", "console_id" => "xmas.present.small"),
            array("name" => "Christmas Tree", "console_id" => "xmas.tree"),
            array("name" => "Festive Window Garland", "console_id" => "xmas.window.garland"),
            array("name" => "Christmas Door Wreath", "console_id" => "xmasdoorwreath")
        );

        foreach ($items as $item) {
            DB::table('items')->insert([
                'name' => $item['name'],
                'console_id' => $item['console_id'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
