<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = array(
            array("name" => "Handmade Shell", "console_id" => "ammo.handmade.shell", "item_type_id" => 2),
            array("name" => "Nailgun Nails", "console_id" => "ammo.nailgun.nails", "item_type_id" => 2),
            array("name" => "Pistol Bullet", "console_id" => "ammo.pistol", "item_type_id" => 2),
            array("name" => "Incendiary Pistol Bullet", "console_id" => "ammo.pistol.fire", "item_type_id" => 2),
            array("name" => "HV Pistol Ammo", "console_id" => "ammo.pistol.hv", "item_type_id" => 2),
            array("name" => "5.56 Rifle Ammo", "console_id" => "ammo.rifle", "item_type_id" => 2),
            array("name" => "Explosive 5.56 Rifle Ammo", "console_id" => "ammo.rifle.explosive", "item_type_id" => 2),
            array("name" => "HV 5.56 Rifle Ammo", "console_id" => "ammo.rifle.hv", "item_type_id" => 2),
            array("name" => "Incendiary 5.56 Rifle Ammo", "console_id" => "ammo.rifle.incendiary", "item_type_id" => 2),
            array("name" => "Rocket", "console_id" => "ammo.rocket.basic", "item_type_id" => 2),
            array("name" => "Incendiary Rocket", "console_id" => "ammo.rocket.fire", "item_type_id" => 2),
            array("name" => "High Velocity Rocket", "console_id" => "ammo.rocket.hv", "item_type_id" => 2),
            array("name" => "Smoke Rocket WIP!!!!", "console_id" => "ammo.rocket.smoke", "item_type_id" => 2),
            array("name" => "12 Gauge Buckshot", "console_id" => "ammo.shotgun", "item_type_id" => 2),
            array("name" => "12 Gauge Slug", "console_id" => "ammo.shotgun.slug", "item_type_id" => 2),
            array("name" => "Anti-Radiation Pills", "console_id" => "antiradpills", "item_type_id" => 5),
            array("name" => "Apple", "console_id" => "apple", "item_type_id" => 5),
            array("name" => "Rotten Apple", "console_id" => "apple.spoiled", "item_type_id" => 5),
            array("name" => "Bone Arrow", "console_id" => "arrow.bone", "item_type_id" => 2),
            array("name" => "Fire Arrow", "console_id" => "arrow.fire", "item_type_id" => 2),
            array("name" => "High Velocity Arrow", "console_id" => "arrow.hv", "item_type_id" => 2),
            array("name" => "Wooden Arrow", "console_id" => "arrow.wooden", "item_type_id" => 2),
            array("name" => "Hide Boots", "console_id" => "attire.hide.boots", "item_type_id" => 4),
            array("name" => "Hide Halterneck", "console_id" => "attire.hide.helterneck", "item_type_id" => 4),
            array("name" => "Hide Pants", "console_id" => "attire.hide.pants", "item_type_id" => 4),
            array("name" => "Hide Poncho", "console_id" => "attire.hide.poncho", "item_type_id" => 4),
            array("name" => "Hide Skirt", "console_id" => "attire.hide.skirt", "item_type_id" => 4),
            array("name" => "Hide Vest", "console_id" => "attire.hide.vest", "item_type_id" => 4),
            array("name" => "Reindeer Antlers", "console_id" => "attire.reindeer.headband", "item_type_id" => 4),
            array("name" => "Auto Turret", "console_id" => "autoturret", "item_type_id" => 6),
            array("name" => "Salvaged Axe", "console_id" => "axe.salvaged", "item_type_id" => 3),
            array("name" => "Bandage", "console_id" => "bandage", "item_type_id" => 7),
            array("name" => "Concrete Barricade", "console_id" => "barricade.concrete", "item_type_id" => 8),
            array("name" => "Metal Barricade", "console_id" => "barricade.metal", "item_type_id" => 8),
            array("name" => "Sandbag Barricade", "console_id" => "barricade.sandbags", "item_type_id" => 8),
            array("name" => "Stone Barricade", "console_id" => "barricade.stone", "item_type_id" => 8),
            array("name" => "Wooden Barricade", "console_id" => "barricade.wood", "item_type_id" => 8),
            array("name" => "Barbed Wooden Barricade", "console_id" => "barricade.woodwire", "item_type_id" => 8),
            array("name" => "Battery - Small", "console_id" => "battery.small", "item_type_id" => 20),
            array("name" => "Barbeque", "console_id" => "bbq", "item_type_id" => 5),
            array("name" => "Raw Bear Meat", "console_id" => "bearmeat", "item_type_id" => 5),
            array("name" => "Burnt Bear Meat", "console_id" => "bearmeat.burned", "item_type_id" => 5),
            array("name" => "Cooked Bear Meat", "console_id" => "bearmeat.cooked", "item_type_id" => 5),
            array("name" => "Bed", "console_id" => "bed", "item_type_id" => 8),
            array("name" => "Black Raspberries", "console_id" => "black.raspberries", "item_type_id" => 5),
            array("name" => "Bleach", "console_id" => "bleach", "item_type_id" => 20),
            array("name" => "Blood", "console_id" => "blood", "item_type_id" => 20),
            array("name" => "Blueberries", "console_id" => "blueberries", "item_type_id" => 5),
            array("name" => "Blueprint", "console_id" => "blueprintbase", "item_type_id" => 20),
            array("name" => "Bone Armor", "console_id" => "bone.armor.suit", "item_type_id" => 4),
            array("name" => "Bone Club", "console_id" => "bone.club", "item_type_id" => 1),
            array("name" => "Bone Fragments", "console_id" => "bone.fragments", "item_type_id" => 9),
            array("name" => "Bota Bag", "console_id" => "botabag", "item_type_id" => 5),
            array("name" => "Hunting Bow", "console_id" => "bow.hunting", "item_type_id" => 1),
            array("name" => "Repair Bench", "console_id" => "box.repair.bench", "item_type_id" => 8),
            array("name" => "Wood Storage Box", "console_id" => "box.wooden", "item_type_id" => 10),
            array("name" => "Large Wood Box", "console_id" => "box.wooden.large", "item_type_id" => 10),
            array("name" => "Bucket Helmet", "console_id" => "bucket.helmet", "item_type_id" => 4),
            array("name" => "Water Bucket", "console_id" => "bucket.water", "item_type_id" => 20),
            array("name" => "Building Plan", "console_id" => "building.planner", "item_type_id" => 20),
            array("name" => "Leather Gloves", "console_id" => "burlap.gloves", "item_type_id" => 4),
            array("name" => "Burlap Headwrap", "console_id" => "burlap.headwrap", "item_type_id" => 4),
            array("name" => "Burlap Shirt", "console_id" => "burlap.shirt", "item_type_id" => 4),
            array("name" => "Burlap Shoes", "console_id" => "burlap.shoes", "item_type_id" => 4),
            array("name" => "Burlap Trousers", "console_id" => "burlap.trousers", "item_type_id" => 4),
            array("name" => "Cactus Flesh", "console_id" => "cactusflesh", "item_type_id" => 5),
            array("name" => "Camp Fire", "console_id" => "campfire", "item_type_id" => 8),
            array("name" => "Can of Beans", "console_id" => "can.beans", "item_type_id" => 5),
            array("name" => "Empty Can Of Beans", "console_id" => "can.beans.empty", "item_type_id" => 20),
            array("name" => "Can of Tuna", "console_id" => "can.tuna", "item_type_id" => 5),
            array("name" => "Empty Tuna Can", "console_id" => "can.tuna.empty", "item_type_id" => 20),
            array("name" => "Candy Cane", "console_id" => "candycane", "item_type_id" => 5),
            array("name" => "Candy Cane Club", "console_id" => "candycaneclub", "item_type_id" => 1),
            array("name" => "CCTV Camera", "console_id" => "cctv.camera", "item_type_id" => 20),
            array("name" => "Ceiling Light", "console_id" => "ceilinglight", "item_type_id" => 8),
            array("name" => "Chair", "console_id" => "chair", "item_type_id" => 8),
            array("name" => "Charcoal", "console_id" => "charcoal", "item_type_id" => 9),
            array("name" => "Burnt Chicken", "console_id" => "chicken.burned", "item_type_id" => 5),
            array("name" => "Cooked Chicken", "console_id" => "chicken.cooked", "item_type_id" => 5),
            array("name" => "Raw Chicken Breast", "console_id" => "chicken.raw", "item_type_id" => 5),
            array("name" => "Spoiled Chicken", "console_id" => "chicken.spoiled", "item_type_id" => 5),
            array("name" => "Chocolate Bar", "console_id" => "chocholate", "item_type_id" => 5),
            array("name" => "Corn Clone", "console_id" => "clone.corn", "item_type_id" => 8),
            array("name" => "Hemp Clone", "console_id" => "clone.hemp", "item_type_id" => 8),
            array("name" => "Pumpkin Plant Clone", "console_id" => "clone.pumpkin", "item_type_id" => 8),
            array("name" => "Cloth", "console_id" => "cloth", "item_type_id" => 9),
            array("name" => "Coal :(", "console_id" => "coal", "item_type_id" => 20),
            array("name" => "Coffee Can Helmet", "console_id" => "coffeecan.helmet", "item_type_id" => 4),
            array("name" => "Corn", "console_id" => "corn", "item_type_id" => 5),
            array("name" => "Crossbow", "console_id" => "crossbow", "item_type_id" => 1),
            array("name" => "Crude Oil", "console_id" => "crude.oil", "item_type_id" => 9),
            array("name" => "Tool Cupboard", "console_id" => "cupboard.tool", "item_type_id" => 8),
            array("name" => "Bone Helmet", "console_id" => "deer.skull.mask", "item_type_id" => 4),
            array("name" => "Burnt Deer Meat", "console_id" => "deermeat.burned", "item_type_id" => 5),
            array("name" => "Cooked Deer Meat", "console_id" => "deermeat.cooked", "item_type_id" => 5),
            array("name" => "Raw Deer Meat", "console_id" => "deermeat.raw", "item_type_id" => 5),
            array("name" => "Door Closer", "console_id" => "door.closer", "item_type_id" => 8),
            array("name" => "Sheet Metal Double Door", "console_id" => "door.double.hinged.metal", "item_type_id" => 8),
            array("name" => "Armored Double Door", "console_id" => "door.double.hinged.toptier", "item_type_id" => 8),
            array("name" => "Wood Double Door", "console_id" => "door.double.hinged.wood", "item_type_id" => 8),
            array("name" => "Sheet Metal Door", "console_id" => "door.hinged.metal", "item_type_id" => 8),
            array("name" => "Armored Door", "console_id" => "door.hinged.toptier", "item_type_id" => 8),
            array("name" => "Wooden Door", "console_id" => "door.hinged.wood", "item_type_id" => 8),
            array("name" => "Door Key", "console_id" => "door.key", "item_type_id" => 20),
            array("name" => "Drop Box", "console_id" => "dropbox", "item_type_id" => 8),
            array("name" => "Duct Tape", "console_id" => "ducttape", "item_type_id" => 20),
            array("name" => "Satchel Charge", "console_id" => "explosive.satchel", "item_type_id" => 1),
            array("name" => "Timed Explosive Charge", "console_id" => "explosive.timed", "item_type_id" => 1),
            array("name" => "Explosives", "console_id" => "explosives", "item_type_id" => 9),
            array("name" => "m-facialhair01", "console_id" => "facialhair.style01", "item_type_id" => 20),
            array("name" => "Animal Fat", "console_id" => "fat.animal", "item_type_id" => 8),
            array("name" => "f-hairstyle-1", "console_id" => "female_hairstyle_01", "item_type_id" => 20),
            array("name" => "f-hairstyle-2", "console_id" => "female_hairstyle_02", "item_type_id" => 20),
            array("name" => "f-hairstyle-3", "console_id" => "female_hairstyle_03", "item_type_id" => 20),
            array("name" => "f-hairstyle-5", "console_id" => "female_hairstyle_05", "item_type_id" => 20),
            array("name" => "f-armpit01", "console_id" => "femalearmpithair.style01", "item_type_id" => 20),
            array("name" => "f-eyebrow01", "console_id" => "femaleeyebrow.style01", "item_type_id" => 20),
            array("name" => "f-pubic01", "console_id" => "femalepubichair.style01", "item_type_id" => 20),
            array("name" => "Stone Fireplace", "console_id" => "fireplace.stone", "item_type_id" => 8),
            array("name" => "Cooked Fish", "console_id" => "fish.cooked", "item_type_id" => 5),
            array("name" => "Minnows", "console_id" => "fish.minnows", "item_type_id" => 8),
            array("name" => "Raw Fish", "console_id" => "fish.raw", "item_type_id" => 5),
            array("name" => "Small Trout", "console_id" => "fish.troutsmall", "item_type_id" => 5),
            array("name" => "Handmade Fishing Rod", "console_id" => "fishingrod.handmade", "item_type_id" => 3),
            array("name" => "Survival Fish Trap", "console_id" => "fishtrap.small", "item_type_id" => 8),
            array("name" => "Flame Thrower", "console_id" => "flamethrower", "item_type_id" => 1),
            array("name" => "Flame Turret", "console_id" => "flameturret", "item_type_id" => 6),
            array("name" => "Flare", "console_id" => "flare", "item_type_id" => 8),
            array("name" => "Flashlight", "console_id" => "flashlight.held", "item_type_id" => 3),
            array("name" => "Floor grill", "console_id" => "floor.grill", "item_type_id" => 8),
            array("name" => "Ladder Hatch", "console_id" => "floor.ladder.hatch", "item_type_id" => 8),
            array("name" => "Fridge", "console_id" => "fridge", "item_type_id" => 10),
            array("name" => "Acoustic Guitar", "console_id" => "fun.guitar", "item_type_id" => 20),
            array("name" => "Furnace", "console_id" => "furnace", "item_type_id" => 8),
            array("name" => "Large Furnace", "console_id" => "furnace.large", "item_type_id" => 8),
            array("name" => "High External Stone Gate", "console_id" => "gates.external.high.stone", "item_type_id" => 8),
            array("name" => "High External Wooden Gate", "console_id" => "gates.external.high.wood", "item_type_id" => 8),
            array("name" => "Gears", "console_id" => "gears", "item_type_id" => 9),
            array("name" => "Wind Turbine", "console_id" => "generator.wind.scrap", "item_type_id" => 20),
            array("name" => "Glowing Eyes", "console_id" => "gloweyes", "item_type_id" => 20),
            array("name" => "Glue", "console_id" => "glue", "item_type_id" => 20),
            array("name" => "Granola Bar", "console_id" => "granolabar", "item_type_id" => 5),
            array("name" => "Beancan Grenade", "console_id" => "grenade.beancan", "item_type_id" => 1),
            array("name" => "F1 Grenade", "console_id" => "grenade.f1", "item_type_id" => 1),
            array("name" => "Gun Powder", "console_id" => "gunpowder", "item_type_id" => 9),
            array("name" => "Shotgun Trap", "console_id" => "guntrap", "item_type_id" => 6),
            array("name" => "Hammer", "console_id" => "hammer", "item_type_id" => 3),
            array("name" => "Salvaged Hammer", "console_id" => "hammer.salvaged", "item_type_id" => 3),
            array("name" => "Beenie Hat", "console_id" => "hat.beenie", "item_type_id" => 4),
            array("name" => "Boonie Hat", "console_id" => "hat.boonie", "item_type_id" => 4),
            array("name" => "Candle Hat", "console_id" => "hat.candle", "item_type_id" => 4),
            array("name" => "Baseball Cap", "console_id" => "hat.cap", "item_type_id" => 4),
            array("name" => "Miners Hat", "console_id" => "hat.miner", "item_type_id" => 4),
            array("name" => "Wolf Headdress", "console_id" => "hat.wolf", "item_type_id" => 4),
            array("name" => "Hatchet", "console_id" => "hatchet", "item_type_id" => 3),
            array("name" => "Hazmat Suit", "console_id" => "hazmatsuit", "item_type_id" => 4),
            array("name" => "Scientist Suit", "console_id" => "hazmatsuit_scientist", "item_type_id" => 4),
            array("name" => "Heavy Plate Helmet", "console_id" => "heavy.plate.helmet", "item_type_id" => 4),
            array("name" => "Heavy Plate Jacket", "console_id" => "heavy.plate.jacket", "item_type_id" => 4),
            array("name" => "Heavy Plate Pants", "console_id" => "heavy.plate.pants", "item_type_id" => 4),
            array("name" => "Hoodie", "console_id" => "hoodie", "item_type_id" => 4),
            array("name" => "Burnt Horse Meat", "console_id" => "horsemeat.burnt", "item_type_id" => 5),
            array("name" => "Cooked Horse Meat", "console_id" => "horsemeat.cooked", "item_type_id" => 5),
            array("name" => "Raw Horse Meat", "console_id" => "horsemeat.raw", "item_type_id" => 5),
            array("name" => "High Quality Metal Ore", "console_id" => "hq.metal.ore", "item_type_id" => 9),
            array("name" => "Burnt Human Meat", "console_id" => "humanmeat.burned", "item_type_id" => 5),
            array("name" => "Cooked Human Meat", "console_id" => "humanmeat.cooked", "item_type_id" => 5),
            array("name" => "Raw Human Meat", "console_id" => "humanmeat.raw", "item_type_id" => 5),
            array("name" => "Spoiled Human Meat", "console_id" => "humanmeat.spoiled", "item_type_id" => 5),
            array("name" => "Salvaged Icepick", "console_id" => "icepick.salvaged", "item_type_id" => 3),
            array("name" => "Jacket", "console_id" => "jacket", "item_type_id" => 4),
            array("name" => "Snow Jacket - Red", "console_id" => "jacket.snow", "item_type_id" => 4),
            array("name" => "Jack O Lantern Angry", "console_id" => "jackolantern.angry", "item_type_id" => 8),
            array("name" => "Jack O Lantern Happy", "console_id" => "jackolantern.happy", "item_type_id" => 8),
            array("name" => "Bone Knife", "console_id" => "knife.bone", "item_type_id" => 1),
            array("name" => "Wooden Ladder", "console_id" => "ladder.wooden.wall", "item_type_id" => 8),
            array("name" => "Lantern", "console_id" => "lantern", "item_type_id" => 8),
            array("name" => "Large Medkit", "console_id" => "largemedkit", "item_type_id" => 7),
            array("name" => "Leather", "console_id" => "leather", "item_type_id" => 9),
            array("name" => "M249", "console_id" => "lmg.m249", "item_type_id" => 1),
            array("name" => "Code Lock", "console_id" => "lock.code", "item_type_id" => 8),
            array("name" => "Key Lock", "console_id" => "lock.key", "item_type_id" => 8),
            array("name" => "Locker", "console_id" => "locker", "item_type_id" => 10),
            array("name" => "Longsword", "console_id" => "longsword", "item_type_id" => 1),
            array("name" => "Low Grade Fuel", "console_id" => "lowgradefuel", "item_type_id" => 9),
            array("name" => "Mace", "console_id" => "mace", "item_type_id" => 1),
            array("name" => "Machete", "console_id" => "machete", "item_type_id" => 1),
            array("name" => "Mail Box", "console_id" => "mailbox", "item_type_id" => 8),
            array("name" => "m-facialhair02", "console_id" => "male.facialhair.style02", "item_type_id" => 20),
            array("name" => "m-facialhair03", "console_id" => "male.facialhair.style03", "item_type_id" => 20),
            array("name" => "m-facialhair04", "console_id" => "male.facialhair.style04", "item_type_id" => 20),
            array("name" => "m-hairstyle-1", "console_id" => "male_hairstyle_01", "item_type_id" => 20),
            array("name" => "m-hairstyle-2", "console_id" => "male_hairstyle_02", "item_type_id" => 20),
            array("name" => "m-hairstyle-3", "console_id" => "male_hairstyle_03", "item_type_id" => 20),
            array("name" => "m-hairstyle-4", "console_id" => "male_hairstyle_04", "item_type_id" => 20),
            array("name" => "m-hairstyle-5", "console_id" => "male_hairstyle_05", "item_type_id" => 20),
            array("name" => "m-armpit01", "console_id" => "malearmpithair.style01", "item_type_id" => 20),
            array("name" => "m-eyebrow01", "console_id" => "maleeyebrow.style01", "item_type_id" => 20),
            array("name" => "m-pubic01", "console_id" => "malepubichair.style01", "item_type_id" => 20),
            array("name" => "Paper Map", "console_id" => "map", "item_type_id" => 20),
            array("name" => "Improvised Balaclava", "console_id" => "mask.balaclava", "item_type_id" => 4),
            array("name" => "Bandana Mask", "console_id" => "mask.bandana", "item_type_id" => 4),
            array("name" => "Raw Pork", "console_id" => "meat.boar", "item_type_id" => 5),
            array("name" => "Burnt Pork", "console_id" => "meat.pork.burned", "item_type_id" => 5),
            array("name" => "Cooked Pork", "console_id" => "meat.pork.cooked", "item_type_id" => 5),
            array("name" => "Metal Facemask", "console_id" => "metal.facemask", "item_type_id" => 4),
            array("name" => "Metal Fragments", "console_id" => "metal.fragments", "item_type_id" => 9),
            array("name" => "Metal Ore", "console_id" => "metal.ore", "item_type_id" => 9),
            array("name" => "Metal Chest Plate", "console_id" => "metal.plate.torso", "item_type_id" => 4),
            array("name" => "High Quality Metal", "console_id" => "metal.refined", "item_type_id" => 9),
            array("name" => "Metal Blade", "console_id" => "metalblade", "item_type_id" => 20),
            array("name" => "Metal Pipe", "console_id" => "metalpipe", "item_type_id" => 20),
            array("name" => "Metal Spring", "console_id" => "metalspring", "item_type_id" => 20),
            array("name" => "Pump Jack", "console_id" => "mining.pumpjack", "item_type_id" => 20),
            array("name" => "Mining Quarry", "console_id" => "mining.quarry", "item_type_id" => 8),
            array("name" => "Mushroom", "console_id" => "mushroom", "item_type_id" => 5),
            array("name" => "Note", "console_id" => "note", "item_type_id" => 7),
            array("name" => "Pants", "console_id" => "pants", "item_type_id" => 4),
            array("name" => "Shorts", "console_id" => "pants.shorts", "item_type_id" => 4),
            array("name" => "Paper", "console_id" => "paper", "item_type_id" => 9),
            array("name" => "Pickaxe", "console_id" => "pickaxe", "item_type_id" => 3),
            array("name" => "Eoka Pistol", "console_id" => "pistol.eoka", "item_type_id" => 1),
            array("name" => "M92 Pistol", "console_id" => "pistol.m92", "item_type_id" => 1),
            array("name" => "Nailgun", "console_id" => "pistol.nailgun", "item_type_id" => 1),
            array("name" => "Python Revolver", "console_id" => "pistol.python", "item_type_id" => 1),
            array("name" => "Revolver", "console_id" => "pistol.revolver", "item_type_id" => 1),
            array("name" => "Semi-Automatic Pistol", "console_id" => "pistol.semiauto", "item_type_id" => 1),
            array("name" => "Large Planter Box", "console_id" => "planter.large", "item_type_id" => 8),
            array("name" => "Small Planter Box", "console_id" => "planter.small", "item_type_id" => 8),
            array("name" => "Pookie Bear", "console_id" => "pookie.bear", "item_type_id" => 20),
            array("name" => "Empty Propane Tank", "console_id" => "propanetank", "item_type_id" => 20),
            array("name" => "Pumpkin", "console_id" => "pumpkin", "item_type_id" => 5),
            array("name" => "Research Table", "console_id" => "research.table", "item_type_id" => 8),
            array("name" => "Research Paper", "console_id" => "researchpaper", "item_type_id" => 20),
            array("name" => "Assault Rifle", "console_id" => "rifle.ak", "item_type_id" => 1),
            array("name" => "Bolt Action Rifle", "console_id" => "rifle.bolt", "item_type_id" => 1),
            array("name" => "LR-300 Assault Rifle", "console_id" => "rifle.lr300", "item_type_id" => 1),
            array("name" => "Semi-Automatic Rifle", "console_id" => "rifle.semiauto", "item_type_id" => 1),
            array("name" => "Rifle Body", "console_id" => "riflebody", "item_type_id" => 20),
            array("name" => "Riot Helmet", "console_id" => "riot.helmet", "item_type_id" => 4),
            array("name" => "Road Sign Jacket", "console_id" => "roadsign.jacket", "item_type_id" => 4),
            array("name" => "Road Sign Kilt", "console_id" => "roadsign.kilt", "item_type_id" => 4),
            array("name" => "Road Signs", "console_id" => "roadsigns", "item_type_id" => 20),
            array("name" => "Rock", "console_id" => "rock", "item_type_id" => 1),
            array("name" => "Rocket Launcher", "console_id" => "rocket.launcher", "item_type_id" => 1),
            array("name" => "Rope", "console_id" => "rope", "item_type_id" => 20),
            array("name" => "Rug", "console_id" => "rug", "item_type_id" => 8),
            array("name" => "Rug Bear Skin", "console_id" => "rug.bear", "item_type_id" => 8),
            array("name" => "Salvaged Cleaver", "console_id" => "salvaged.cleaver", "item_type_id" => 1),
            array("name" => "Salvaged Sword", "console_id" => "salvaged.sword", "item_type_id" => 1),
            array("name" => "Santa Hat", "console_id" => "santahat", "item_type_id" => 4),
            array("name" => "Scarecrow", "console_id" => "scarecrow", "item_type_id" => 8),
            array("name" => "Scrap", "console_id" => "scrap", "item_type_id" => 20),
            array("name" => "Search Light", "console_id" => "searchlight", "item_type_id" => 8),
            array("name" => "Corn Seed", "console_id" => "seed.corn", "item_type_id" => 8),
            array("name" => "Hemp Seed", "console_id" => "seed.hemp", "item_type_id" => 8),
            array("name" => "Pumpkin Seed", "console_id" => "seed.pumpkin", "item_type_id" => 8),
            array("name" => "Semi Automatic Body", "console_id" => "semibody", "item_type_id" => 20),
            array("name" => "Sewing Kit", "console_id" => "sewingkit", "item_type_id" => 20),
            array("name" => "Sheet Metal", "console_id" => "sheetmetal", "item_type_id" => 20),
            array("name" => "Salvaged Shelves", "console_id" => "shelves", "item_type_id" => 10),
            array("name" => "Shirt", "console_id" => "shirt.collared", "item_type_id" => 4),
            array("name" => "Tank Top", "console_id" => "shirt.tanktop", "item_type_id" => 4),
            array("name" => "Boots", "console_id" => "shoes.boots", "item_type_id" => 4),
            array("name" => "Double Barrel Shotgun", "console_id" => "shotgun.double", "item_type_id" => 1),
            array("name" => "Pump Shotgun", "console_id" => "shotgun.pump", "item_type_id" => 1),
            array("name" => "Waterpipe Shotgun", "console_id" => "shotgun.waterpipe", "item_type_id" => 1),
            array("name" => "Metal horizontal embrasure", "console_id" => "shutter.metal.embrasure.a", "item_type_id" => 8),
            array("name" => "Metal Vertical embrasure", "console_id" => "shutter.metal.embrasure.b", "item_type_id" => 8),
            array("name" => "Wood Shutters", "console_id" => "shutter.wood.a", "item_type_id" => 8),
            array("name" => "Two Sided Hanging Sign", "console_id" => "sign.hanging", "item_type_id" => 8),
            array("name" => "Large Banner Hanging", "console_id" => "sign.hanging.banner.large", "item_type_id" => 8),
            array("name" => "Two Sided Ornate Hanging Sign", "console_id" => "sign.hanging.ornate", "item_type_id" => 8),
            array("name" => "Landscape Picture Frame", "console_id" => "sign.pictureframe.landscape", "item_type_id" => 8),
            array("name" => "Portrait Picture Frame", "console_id" => "sign.pictureframe.portrait", "item_type_id" => 8),
            array("name" => "Tall Picture Frame", "console_id" => "sign.pictureframe.tall", "item_type_id" => 8),
            array("name" => "XL Picture Frame", "console_id" => "sign.pictureframe.xl", "item_type_id" => 8),
            array("name" => "XXL Picture Frame", "console_id" => "sign.pictureframe.xxl", "item_type_id" => 8),
            array("name" => "Large Banner on pole", "console_id" => "sign.pole.banner.large", "item_type_id" => 8),
            array("name" => "Double Sign Post", "console_id" => "sign.post.double", "item_type_id" => 8),
            array("name" => "Single Sign Post", "console_id" => "sign.post.single", "item_type_id" => 8),
            array("name" => "One Sided Town Sign Post", "console_id" => "sign.post.town", "item_type_id" => 8),
            array("name" => "Two Sided Town Sign Post", "console_id" => "sign.post.town.roof", "item_type_id" => 8),
            array("name" => "Huge Wooden Sign", "console_id" => "sign.wooden.huge", "item_type_id" => 8),
            array("name" => "Large Wooden Sign", "console_id" => "sign.wooden.large", "item_type_id" => 8),
            array("name" => "Wooden Sign", "console_id" => "sign.wooden.medium", "item_type_id" => 8),
            array("name" => "Small Wooden Sign", "console_id" => "sign.wooden.small", "item_type_id" => 8),
            array("name" => "Human Skull", "console_id" => "skull.human", "item_type_id" => 20),
            array("name" => "Wolf Skull", "console_id" => "skull.wolf", "item_type_id" => 20),
            array("name" => "Skull Fire Pit", "console_id" => "skull_fire_pit", "item_type_id" => 20),
            array("name" => "Sleeping Bag", "console_id" => "sleepingbag", "item_type_id" => 8),
            array("name" => "Small Oil Refinery", "console_id" => "small.oil.refinery", "item_type_id" => 8),
            array("name" => "Small Water Bottle", "console_id" => "smallwaterbottle", "item_type_id" => 20),
            array("name" => "Custom SMG", "console_id" => "smg.2", "item_type_id" => 1),
            array("name" => "MP5A4", "console_id" => "smg.mp5", "item_type_id" => 1),
            array("name" => "Thompson", "console_id" => "smg.thompson", "item_type_id" => 1),
            array("name" => "SMG Body", "console_id" => "smgbody", "item_type_id" => 1),
            array("name" => "Snowball", "console_id" => "snowball", "item_type_id" => 20),
            array("name" => "Snowman", "console_id" => "snowman", "item_type_id" => 8),
            array("name" => "Stone Spear", "console_id" => "spear.stone", "item_type_id" => 1),
            array("name" => "Wooden Spear", "console_id" => "spear.wooden", "item_type_id" => 1),
            array("name" => "Wooden Floor Spikes", "console_id" => "spikes.floor", "item_type_id" => 6),
            array("name" => "Spinning wheel", "console_id" => "spinner.wheel", "item_type_id" => 20),
            array("name" => "Small Stash", "console_id" => "stash.small", "item_type_id" => 10),
            array("name" => "Sticks", "console_id" => "sticks", "item_type_id" => 20),
            array("name" => "SUPER Stocking", "console_id" => "stocking.large", "item_type_id" => 20),
            array("name" => "Small Stocking", "console_id" => "stocking.small", "item_type_id" => 20),
            array("name" => "Stone Pickaxe", "console_id" => "stone.pickaxe", "item_type_id" => 3),
            array("name" => "Stone Hatchet", "console_id" => "stonehatchet", "item_type_id" => 3),
            array("name" => "Stones", "console_id" => "stones", "item_type_id" => 9),
            array("name" => "Sulfur", "console_id" => "sulfur", "item_type_id" => 9),
            array("name" => "Sulfur Ore", "console_id" => "sulfur.ore", "item_type_id" => 9),
            array("name" => "Supply Signal", "console_id" => "supply.signal", "item_type_id" => 8),
            array("name" => "Survey Charge", "console_id" => "surveycharge", "item_type_id" => 1),
            array("name" => "Medical Syringe", "console_id" => "syringe.medical", "item_type_id" => 7),
            array("name" => "Table", "console_id" => "table", "item_type_id" => 8),
            array("name" => "Reactive Target", "console_id" => "target.reactive", "item_type_id" => 8),
            array("name" => "Targeting Computer", "console_id" => "targeting.computer", "item_type_id" => 20),
            array("name" => "Tarp", "console_id" => "tarp", "item_type_id" => 20),
            array("name" => "Tech Trash", "console_id" => "techparts", "item_type_id" => 20),
            array("name" => "Binoculars", "console_id" => "tool.binoculars", "item_type_id" => 3),
            array("name" => "Camera", "console_id" => "tool.camera", "item_type_id" => 20),
            array("name" => "Torch", "console_id" => "torch", "item_type_id" => 3),
            array("name" => "Snap Trap", "console_id" => "trap.bear", "item_type_id" => 1),
            array("name" => "Land Mine", "console_id" => "trap.landmine", "item_type_id" => 1),
            array("name" => "T-Shirt", "console_id" => "tshirt", "item_type_id" => 4),
            array("name" => "Longsleeve T-Shirt", "console_id" => "tshirt.long", "item_type_id" => 4),
            array("name" => "Tuna Can Lamp", "console_id" => "tunalight", "item_type_id" => 8),
            array("name" => "Vending Machine", "console_id" => "vending.machine", "item_type_id" => 10),
            array("name" => "High External Wooden Wall", "console_id" => "wall.external.high", "item_type_id" => 8),
            array("name" => "High External Stone Wall", "console_id" => "wall.external.high.stone", "item_type_id" => 8),
            array("name" => "Prison Cell Wall", "console_id" => "wall.frame.cell", "item_type_id" => 8),
            array("name" => "Prison Cell Gate", "console_id" => "wall.frame.cell.gate", "item_type_id" => 8),
            array("name" => "Chainlink Fence", "console_id" => "wall.frame.fence", "item_type_id" => 8),
            array("name" => "Chainlink Fence Gate", "console_id" => "wall.frame.fence.gate", "item_type_id" => 8),
            array("name" => "Garage Door", "console_id" => "wall.frame.garagedoor", "item_type_id" => 8),
            array("name" => "Netting", "console_id" => "wall.frame.netting", "item_type_id" => 8),
            array("name" => "Shop Front", "console_id" => "wall.frame.shopfront", "item_type_id" => 8),
            array("name" => "Metal Shop Front", "console_id" => "wall.frame.shopfront.metal", "item_type_id" => 8),
            array("name" => "Metal Window Bars", "console_id" => "wall.window.bars.metal", "item_type_id" => 8),
            array("name" => "Reinforced Window Bars", "console_id" => "wall.window.bars.toptier", "item_type_id" => 8),
            array("name" => "Wooden Window Bars", "console_id" => "wall.window.bars.wood", "item_type_id" => 8),
            array("name" => "Reinforced Glass Window", "console_id" => "wall.window.glass.reinforced", "item_type_id" => 8),
            array("name" => "Water", "console_id" => "water", "item_type_id" => 9),
            array("name" => "Water Barrel", "console_id" => "water.barrel", "item_type_id" => 8),
            array("name" => "Large Water Catcher", "console_id" => "water.catcher.large", "item_type_id" => 8),
            array("name" => "Small Water Catcher", "console_id" => "water.catcher.small", "item_type_id" => 8),
            array("name" => "Water Purifier", "console_id" => "water.purifier", "item_type_id" => 8),
            array("name" => "Salt Water", "console_id" => "water.salt", "item_type_id" => 9),
            array("name" => "Water Jug", "console_id" => "waterjug", "item_type_id" => 7),
            array("name" => "Weapon flashlight", "console_id" => "weapon.mod.flashlight", "item_type_id" => 11),
            array("name" => "Holosight", "console_id" => "weapon.mod.holosight", "item_type_id" => 11),
            array("name" => "Weapon Lasersight", "console_id" => "weapon.mod.lasersight", "item_type_id" => 11),
            array("name" => "Muzzle Boost", "console_id" => "weapon.mod.muzzleboost", "item_type_id" => 11),
            array("name" => "Muzzle Brake", "console_id" => "weapon.mod.muzzlebrake", "item_type_id" => 11),
            array("name" => "Silencer", "console_id" => "weapon.mod.silencer", "item_type_id" => 11),
            array("name" => "Simple Handmade Sight", "console_id" => "weapon.mod.simplesight", "item_type_id" => 11),
            array("name" => "4x Zoom Scope", "console_id" => "weapon.mod.small.scope", "item_type_id" => 11),
            array("name" => "Burnt Wolf Meat", "console_id" => "wolfmeat.burned", "item_type_id" => 5),
            array("name" => "Cooked Wolf Meat", "console_id" => "wolfmeat.cooked", "item_type_id" => 5),
            array("name" => "Raw Wolf Meat", "console_id" => "wolfmeat.raw", "item_type_id" => 5),
            array("name" => "Spoiled Wolf Meat", "console_id" => "wolfmeat.spoiled", "item_type_id" => 5),
            array("name" => "Wood", "console_id" => "wood", "item_type_id" => 9),
            array("name" => "Wood Armor Helmet", "console_id" => "wood.armor.helmet", "item_type_id" => 4),
            array("name" => "Wood Chestplate", "console_id" => "wood.armor.jacket", "item_type_id" => 4),
            array("name" => "Wood Armor Pants", "console_id" => "wood.armor.pants", "item_type_id" => 4),
            array("name" => "Work Bench Level 1", "console_id" => "workbench1", "item_type_id" => 8),
            array("name" => "Work Bench Level 2", "console_id" => "workbench2", "item_type_id" => 8),
            array("name" => "Work Bench Level 3", "console_id" => "workbench3", "item_type_id" => 8),
            array("name" => "Decorative Baubels", "console_id" => "xmas.decoration.baubels", "item_type_id" => 20),
            array("name" => "Decorative Plastic Candy Canes", "console_id" => "xmas.decoration.candycanes", "item_type_id" => 20),
            array("name" => "Decorative Gingerbread Men", "console_id" => "xmas.decoration.gingerbreadmen", "item_type_id" => 20),
            array("name" => "Tree Lights", "console_id" => "xmas.decoration.lights", "item_type_id" => 8),
            array("name" => "Decorative Pinecones", "console_id" => "xmas.decoration.pinecone", "item_type_id" => 20),
            array("name" => "Star Tree Topper", "console_id" => "xmas.decoration.star", "item_type_id" => 20),
            array("name" => "Decorative Tinsel", "console_id" => "xmas.decoration.tinsel", "item_type_id" => 20),
            array("name" => "Festive Doorway Garland", "console_id" => "xmas.door.garland", "item_type_id" => 20),
            array("name" => "Christmas Lights", "console_id" => "xmas.lightstring", "item_type_id" => 8),
            array("name" => "Large Present", "console_id" => "xmas.present.large", "item_type_id" => 7),
            array("name" => "Medium Present", "console_id" => "xmas.present.medium", "item_type_id" => 7),
            array("name" => "Small Present", "console_id" => "xmas.present.small", "item_type_id" => 7),
            array("name" => "Christmas Tree", "console_id" => "xmas.tree", "item_type_id" => 8),
            array("name" => "Festive Window Garland", "console_id" => "xmas.window.garland", "item_type_id" => 20),
            array("name" => "Christmas Door Wreath", "console_id" => "xmasdoorwreath", "item_type_id" => 8)
        );

        foreach ($items as $item) {
            DB::table('items')->insert([
                'name' => $item['name'],
                'console_id' => $item['console_id'],
                'item_type_id' => $item['item_type_id'],
            ]);
        }
    }
}
